/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bilgeadam.cardealers.views;

import com.bilgeadam.cardealers.entity.Car;
import com.bilgeadam.cardealers.repository.CarRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author musty
 */
public class CarPage extends javax.swing.JFrame {

    /**
     * Creates new form CarPage
     */
     DefaultTableModel model;
    CarRepository carRepository;
    List<Car> cars;
    
    public CarPage() {
        initComponents();
        carRepository=new CarRepository();
        model= (DefaultTableModel) car_table.getModel();
        getCars();
        
    }
    
    
    
    private void getCars(){
       
        model.setRowCount(0);
        
      cars= carRepository.findAll();
      
      if(cars!=null){
          
          for (Car car : cars) {
              
              Object [] array={car.getId(),car.getBrand(),car.getCarModel(),car.getModelYear(),car.getDealershipId()}; 
              model.addRow(array);
          }
          
      }
      
      
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        car_table = new javax.swing.JTable();
        search_text = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        brand_label = new javax.swing.JLabel();
        brand_text = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        car_model_label = new javax.swing.JLabel();
        car_model_text = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        model_year_label = new javax.swing.JLabel();
        delete_button = new javax.swing.JButton();
        model_year_text = new javax.swing.JTextField();
        dealership_id_text = new javax.swing.JTextField();
        delership_id_label = new javax.swing.JLabel();
        msj_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        car_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "brand", "car_model", "model_year", "dealership_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        car_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                car_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(car_table);
        if (car_table.getColumnModel().getColumnCount() > 0) {
            car_table.getColumnModel().getColumn(0).setResizable(false);
            car_table.getColumnModel().getColumn(1).setResizable(false);
            car_table.getColumnModel().getColumn(2).setResizable(false);
            car_table.getColumnModel().getColumn(4).setResizable(false);
        }

        search_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                search_textMouseReleased(evt);
            }
        });
        search_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_textKeyReleased(evt);
            }
        });

        brand_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand_label.setText("Brand");

        brand_text.setEditable(false);

        add_button.setText("AddCar");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        car_model_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        car_model_label.setText("Car Model");

        car_model_text.setEditable(false);

        update_button.setText("Update Car");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        model_year_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        model_year_label.setText("Model Year");

        delete_button.setText("Delete Car");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        model_year_text.setEditable(false);

        dealership_id_text.setEditable(false);

        delership_id_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delership_id_label.setText("Dealership id");

        msj_text.setFont(new java.awt.Font("Calibri Light", 2, 14)); // NOI18N
        msj_text.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msj_text, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(search_text, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brand_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brand_text, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(car_model_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(car_model_text, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(model_year_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(model_year_text, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delership_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dealership_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brand_text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(brand_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(car_model_text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(car_model_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(model_year_text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(model_year_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dealership_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(delership_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(msj_text)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void car_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_car_tableMouseClicked
            int selectedRow=car_table.getSelectedRow();
            brand_text.setText(model.getValueAt(selectedRow, 1).toString());
            car_model_text.setText(model.getValueAt(selectedRow, 2).toString());
            model_year_text.setText(model.getValueAt(selectedRow, 3).toString());
          dealership_id_text.setText(model.getValueAt(selectedRow, 4).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_car_tableMouseClicked

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        AddCarPage addCarPage=new AddCarPage();
        addCarPage.setVisible(true);
        
     
    }//GEN-LAST:event_add_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
   
        
       String brand=brand_text.getText();
       String car_model=car_model_text.getText();
       String model_year=model_year_text.getText();
      
       Car car=new Car(brand, car_model, model_year);
           int selectedRow=car_table.getSelectedRow();
       if (selectedRow==-1) {
            if (model.getRowCount()==0) {
                msj_text.setText("Araba Tablosu Suan bos");
            }else{
                 msj_text.setText("Lutfen guncellenecek bir araba secin");
            }
        }else{
       
    Long dealrshipID=Long.parseLong(dealership_id_text.getText());
    car.setDealershipId(dealrshipID);
       Long id= (Long) model.getValueAt(selectedRow, 0);
       car.setId(id);
       UpdateCarPage updateCarPage=new UpdateCarPage();
       
       
       updateCarPage.transferValues(car);
       updateCarPage.setCar(car);
    
        setVisible(false);
        updateCarPage.setVisible(true);
       }
       
       
       
       
       

// TODO add your handling code here:
    }//GEN-LAST:event_update_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        msj_text.setText("");
        int selectedRow=car_table.getSelectedRow();
      
         if (selectedRow==-1) {
            if (model.getRowCount()==0) {
                msj_text.setText("Araba Tablosu Suan bos");
            }else{
                 msj_text.setText("Lutfen guncellenecek bir araba secin");
            }
            
            
        }else{
            
            int id=Integer.parseInt(model.getValueAt(selectedRow, 0).toString()) ;
            int secim=JOptionPane.showConfirmDialog(this, "Araba kaydını silmek istediğiniz eminmisiniz"," Dikkat!",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);

if(secim==JOptionPane.OK_OPTION){
    
     carRepository.delete(id);
            getCars();
             msj_text.setText("Araba Basarıyla silindi");
             
             clearTextAreas();
}
           
        }
     
        
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void search_textMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_textMouseReleased
         
    }//GEN-LAST:event_search_textMouseReleased

    private void search_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_textKeyReleased
         String search=search_text.getText();

        search(search);
    }//GEN-LAST:event_search_textKeyReleased

       public void search(String search){
        
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        
        car_table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }
    
    
     public void clearTextAreas(){
        brand_text.setText("");
        car_model_text.setText("");
        model_year_text.setText("");
        dealership_id_text.setText("");
    }
    
 
                                 
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel brand_label;
    private javax.swing.JTextField brand_text;
    private javax.swing.JLabel car_model_label;
    private javax.swing.JTextField car_model_text;
    private javax.swing.JTable car_table;
    private javax.swing.JTextField dealership_id_text;
    private javax.swing.JLabel delership_id_label;
    private javax.swing.JButton delete_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel model_year_label;
    private javax.swing.JTextField model_year_text;
    private javax.swing.JLabel msj_text;
    private javax.swing.JTextField search_text;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
